### PR TITLE
support pandoc path

### PR DESCRIPTION
**Pull request by rexdf**
If pandoc path has whitespace, there will be an error about #4 .

### CODE REVIEW

**Comment by rexdf** [comment]
@yyjhao

**Comment by yyjhao** [comment]
Can you just try adding the pandoc path to the user paths settings?

**Comment by rexdf** [comment]
On my Windows, I don't want to put pandoc to system PATH.

I install pandoc in `D:\Program Files\Pandoc`

I tried add `"` or `\"` or `'` for it. Nothing will work.

**Comment by yyjhao** [comment]
ok. So do you mean that with this fix, there is still going to be an error?

**Comment by rexdf** [comment]
If I use `"command": "D:\\Program Files\\Pandoc\\pandoc.exe -t HTML5 --mathjax", `
or `"command": "\"D:\\Program Files\\Pandoc\\pandoc.exe\" -t HTML5 --mathjax", `  both not work.

After this patch,

If set a pandoc_path in `User/sublime-text-markmon.sublime-settings`, this problem can be fixed.
markmon

**Comment by yyjhao** [comment]
Cool thanks for looking at this.

**Pull request merged**
